### ISSUE TITLE
Auto Approved Sub Tasks Hang

### ISSUE THREAD

**Issue by timthesinner** [RooVetGit/Roo-Code#3107]
### App Version

v3.15.1

### API Provider

OpenRouter

### Model Used

All Models

### Actual vs. Expected Behavior

When the AI is allowed to auto complete sub tasks the workflow hangs at user approval (that is unneeded).

Orchestrators are able to auto submit sub tasks without issue, it is the subtask return that is having problems.

When auto complete sub task is not active, the workflow ends and you can click a button to head back to the orchestrator.  While it is hung the only thing you can do is terminate the task by exiting out which tells the orchestrator that the task failed.

<img width="550" alt="Image" src="https://github.com/user-attachments/assets/9ddb6a64-522d-4961-99ab-46bbf32387d2" />

### Detailed Steps to Reproduce

1. Activate subtask auto approval
2. Give an orchestrator a task to break down
2. Let that orchestrator delegate a task to a different mode
3. Wait for that mode to complete which will hang the workflow

### Relevant API Request Output

```shell

```

**Comment by timthesinner** [comment]
I was able to confirm that issue does not exist on `v3.14.3` by manually rolling back.

This is not an issue with cancellation of the task, the sub task was completed successfully.  It just seems that on the latest version, when that subtask completes the workflow hangs, like it is looking for the user to click the button (but as you can see in the picture the buttons and chat input are disabled)

Obviously I would prefer the AI to just complete the sub task and proceed as I am not expecting to review every minor change, I want to review the overall PR

**Comment by redlotusaustin** [comment]
I've had similar happen to me but I'm not sure if it's exactly the same because so far I think it's only happened to me when the last task is a failed python unit test:

![Image](https://github.com/user-attachments/assets/f752f696-f886-4ff3-ab91-991dc81c1032)

The result is the same though: Roo becomes soft-locked and I have to close the task and start a new one.

**Comment by SaigonMike** [comment]
I have had the same issue three times today, sub task tells me "Roo wants to finish this subtask", it then ask me to confirm that everything looks good, so that it can return to the parent task.
There is no way to confirm as the input field is disabled and Subtasks are set to auto. This is happening on the same task 3 times in a row.

**Comment by DavidBoman** [comment]
+1

![Image](https://github.com/user-attachments/assets/47bb1779-aa2c-4f3c-9878-e1838459259e)

**Comment by sealad886** [comment]
For me, this exact issue appears to be occuring because there are edits still in-progress (but that, of course, aren't actually happening) earlier in the chain history:

![Image](https://github.com/user-attachments/assets/97d7b45d-b23a-458c-98e4-17497256cd1b)

My current workaround is to copy the `attempt_completion` output displayed by the subtask, "terminate" the task (using the X at the top right), then cancel the step in the parent task when it says "the user terminated the subtask" and say something like: 

````txt
Here is the `attempt_completion` result:

```txt
<pasted result>
```
````

**Comment by mrubens** [comment]
Does rolling back to 3.15.1 fix for you all? Trying to narrow down the version where this started happening - I'm struggling to repro.

**Comment by mrubens** [comment]
Thanks, I think this could be related to subtasks trying to run commands as part of completion. @cte and I are taking a look. Thank you all for the help.

**Comment by redlotusaustin** [comment]
That does seem to be the problem for me. The task shows as completed in this screenshot, then coverage tests run and it hangs:

![Image](https://github.com/user-attachments/assets/a65f60c3-e079-4eea-8933-ccc61c3ddb1c)

Thank you for all of your hard work!

**Comment by sealad886** [comment]
I am still getting this issue for the same root cause in 3.15.1, although MUCH less frequently.

**Comment by kokorolx** [comment]
I'm facing same issue, while it complete the subtask but can not return to parent task.
I'm using `Version: 3.15.3`
<img width="440" alt="Image" src="https://github.com/user-attachments/assets/5a740f22-6928-4ace-b95c-94c508539766" />

**Comment by mrubens** [comment]
Can you try 3.15.4? We released a hopeful fix.

**Comment by hannesrudolph** [comment]
Let us know if this is still an issue. if it is I will reopen.

**Comment by bonifacsolyom** [comment]
I'm on version 3.19.3 and I'm still encountering this bug. Roo tried to run a command while completing the subtask and I am also stuck at the same screen as everyone else. I think it wasn't even _trying_ to run a command, it was just summarizing the task and mentioned how to run the code, and roo interpreted it as the AI trying to run a command (not a 100% sure about this though). Seems like this issue is not yet fixed
